version: '3.8'

services:
  db:
    image: postgres:latest
    logging:
      options:
        max-size: "200k"
        max-file: "1"
    container_name: postgres_db
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  auth-service-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '81:81'
    container_name: 'arcana-auth-service-dev'
    restart: always
    volumes:
      - ./:/app
    logging:
      options:
        max-size: "200k"
        max-file: "1"

volumes:
  db_data: