# Bulid environment
FROM golang:1.22-alpine

WORKDIR /app

RUN apk update && apk add gcc

RUN apk add --no-cache build-base git

RUN go install github.com/air-verse/air@latest

COPY go.mod go.sum ./
RUN go mod download

CMD ["air"]