version: '3.8'

services:
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '81:81'
    container_name: 'arcana-auth-service'
    restart: always
    logging:
      options:
        max-size: "200k"
        max-file: "1"

